name: Package Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-12

    steps:
      - name: Get Sources
        uses: actions/checkout@v3

      - name: Build Package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: "13.3"
          
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/RickMortySwiftApiPackageTests.xctest/Contents/MacOS/RickMortySwiftApiPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
